# Generated by Django 3.2.9 on 2021-11-26 03:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_id', models.CharField(max_length=100, unique=True)),
                ('link', models.URLField()),
                ('otp_secret', models.CharField(max_length=100)),
                ('status', models.CharField(default='initiated', max_length=200)),
                ('callback_time', models.DateTimeField(blank=True, null=True)),
                ('creation_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('email', models.CharField(default='', max_length=255)),
                ('phone_sms', models.CharField(default='', max_length=255)),
                ('phone_voice', models.CharField(default='', max_length=255)),
                ('metadata', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
